### ISSUE TITLE
Not a real issue, but where are the CoCo transcodes? Where are the C transcodes?

### ISSUE THREAD

**Issue by cjohn-murphy** [tcdev42/re#1]
Not a real issue, but where are the CoCo transcodes? Where are the C transcodes?
Am I not looking in the right place, or are they coming later; or maybe they are not for public consumption?
But fascinating work! Thanks for everything you post on your blog.

**Comment by tcdev42** [comment]
The transcodes (except Xevious) are not yet public - they will be coming later.
For now, Xevious (WIP) is available [here](https://github.com/jotd666/xevious)
